AGENT_STATUS_IDLE = 0
AGENT_STATUS_PICKUP = 1
AGENT_STATUS_CARRY = 2
AGENT_STATUS_DROPOFF = 3

AGENT_ORIENTATION_NORTH = 0
AGENT_ORIENTATION_EAST = 1
AGENT_ORIENTATION_SOUTH = 2
AGENT_ORIENTATION_WEST = 3
AGENT_ORIENTATIONS = [AGENT_ORIENTATION_NORTH, AGENT_ORIENTATION_EAST, AGENT_ORIENTATION_SOUTH, AGENT_ORIENTATION_WEST]

SQUARE_SYMBOL_EMPTY = 0
SQUARE_SYMBOL_OCCUPIED = 1
